feature: cabins 2.0 (dok-166, dok-162, dok-160)
rubberdok/indok-web pull request #231
Opened 2021-09-10 11:14 UTC by hermanholmoy

#### What problem/feature does this pull request fix/add?
New booking flow. The flow is as follows:
1. Choose check in and check out date, as well as which cabin to book.
2. Input contact info and number of internal/external participants.
3. Accept (or decline) the contract.
4. Review a summary of the booking, click send.
5. A mail is sent to Hyttestyret, prompting them to either accept or decline the booking. The user gets a summary mail.
6. When a booking is accepted or declined, the user gets a confirmation mail, and the booking is created.

#### (if not a new problem) How was this problem solved earlier?
Old version had two pages, one for check in/out selection and another for contact info/contract. This solution gave little feedback to the user on how far in the booking process he/she has come. The new version uses a stepper which shows what step the user is on (see screenshot below). 

#### How did I fix this problem?
New stepper component with clear feedback on what the status of the current booking is.

### Checklist

- [ ] All tests have passed
- [x] I have created new tests for this feature (may not be applicable to all pull requests)
- [x] I am pleased with the readability of the code (if not, state where you need input)

### Stepper on the check in/out step
![Screenshot 2021-09-10 at 13 11 25](https://user-images.githubusercontent.com/19520716/132844919-c86e2149-2f22-4bc9-bee1-cb213f5bdde5.png)

2021-10-06 16:08 UTC, larwaa requested changes
This is starting to look really great, just some final polishing then I think we can make this live! 🤩 Massive props for an absolutely amazing effort in refactoring some of the components, and generally increasing the code quality even further! 🚀 I hope you're not discouraged by the amount of comments, it's just a really long PR! The quality really is 👌

2021-10-06 16:36 UTC, hermanholmoy commented on backend/apps/cabins/models.py
> +    timestamp = models.DateTimeField()
Does this make `booking.timestamp = timezone.now()` (in cabins/mutations.py) redundant? Also, I'm assuming you mean `auto_now_add`? https://docs.djangoproject.com/en/3.2/ref/models/fields/#django.db.models.DateField.auto_now_add

2021-10-06 17:17 UTC, larwaa commented on backend/apps/cabins/models.py
> +    timestamp = models.DateTimeField()
Yes and yes 🙈

2021-10-07 21:29 UTC, larwaa commented on frontend/src/pages/cabins/index.tsx
> +            </PermissionRequired>
Keep in mind that `<PermissionRequired />` will return `null` in all cases where the user does not have the required permission, which will necessarily be the case if the user is not logged in. Either move the `<Tooltip />` outside `<PermissionRequired />`, or expand the `<PermissionRequired />` component to accept a fallback-component. See DOK-216 for more information.

2021-10-14 16:36 UTC, larwaa approved these changes
LGTM! 🥳🚀 Can't wait to see this go live! Great job, @hermanholmoy, @sverress, @jorul! A big and important addition to the website, and a gold standard for how to properly test features! ⭐️

2021-10-14 16:38 UTC, merged