✨ feat(#402): add login required component with custom redirect
rubberdok/indok-web pull request #409
Opened 2022-01-27 19:30 UTC by larwaa

## Proposed Changes

- Add `<LoginRequired />`-component
- Add helper function for creating Feide logins with custom redirects
- Replace text on `EventDetails.tsx` with an interactive button

## Types of Changes

- [x] New feature
- [ ] Bug fix
- [x] Enhancement/optimization
- [ ] Refactor
- [ ] Style
- [ ] Build/dependencies
- [ ] Other

## Issue(s) fixed or closed by this PR

- Closes #402 

## Checklist

- [ ] I have added tests to cover my changes (for features/bugs)
- [x] I am pleased with the readability of the code (if not, state where you need input)
- [ ] I have tested the changes and verified that they work and do not break anything (to the best of my ability)

2022-01-27 20:31 UTC, MorganFH commented on frontend/src/components/navbar/NavbarLinks.tsx
> +import { DATAPORTEN_SCOPES, generateFeideLoginUrl } from "@utils/auth";
```suggestion
import { generateFeideLoginUrl } from "@utils/auth";
```

2022-01-27 20:35 UTC, MorganFH commented on frontend/src/utils/auth.ts
>  export const DATAPORTEN_SCOPES = [
```suggestion
const DATAPORTEN_SCOPES = [
```

2022-01-27 20:37 UTC, MorganFH requested changes
Looks good!

If my suggestion above is accepted, can we also replace the now legacy log-in code in `frontend/src/pages/forms/[...formId].tsx`?

2022-01-27 22:08 UTC, larwaa commented
> Looks good!
> 
> If my suggestion above is accepted, can we also replace the now legacy log-in code in `frontend/src/pages/forms/[...formId].tsx`?

Yep, that should be possible, great catch!

2022-01-28 15:42 UTC, MorganFH approved these changes
Very nice!

2022-01-28 16:15 UTC, merged